### ISSUE TITLE
Used versions up to date?

### ISSUE THREAD

**Issue by HummelN7872** [industrial-edge/archiving-and-operation#5]
Are the used versions  up to date? As the it is already released for V1.2 I guess minimum the S7 Connector version is not correct.
==> Please correct the versions

OS: Windows or Linux
Docker minimum V18.09
Docker Compose V2.0 – V2.4
Industrial Edge App Publisher (IEAP) V1.1.14
Industrial Edge Management (IEM) V1.1.11
S7 Connector V1.1.11
S7 Connector Configurator 1.1.14
IE Databus V1.1.10
IE Databus Configurator V1.1.24
Industrial Edge Device (IED) V1.1.0-44
TIA Portal V16
PLC: CPU 1511 FW 2.8.3

**Comment by Boehmi-TB** [comment]
Documentation update including used versions currently in work.
https://github.com/industrial-edge/archiving-and-operation/tree/documentation
